//
//  AppStateRenameTabTests.swift
//  NiceUnitTests
//
//  Tests for the manual-rename path. Two invariants matter:
//    1. After `renameTab`, `applyAutoTitle` must not clobber the title.
//    2. Locking one tab's title must not affect any other tab.
//

import Foundation
import XCTest
@testable import Nice

@MainActor
final class AppStateRenameTabTests: XCTestCase {

    private var appState: AppState!

    override func setUp() {
        super.setUp()
        appState = AppState()
    }

    override func tearDown() {
        appState = nil
        super.tearDown()
    }

    // MARK: - renameTab

    func test_renameTab_setsTitleAndMarksManuallySet() {
        let id = injectTab(title: "New tab")
        appState.renameTab(id: id, to: "My session")

        let after = appState.tab(for: id)
        XCTAssertEqual(after?.title, "My session")
        XCTAssertTrue(after?.titleManuallySet ?? false)
    }

    func test_renameTab_trimsWhitespace() {
        let id = injectTab(title: "New tab")
        appState.renameTab(id: id, to: "   padded   ")
        XCTAssertEqual(appState.tab(for: id)?.title, "padded")
    }

    func test_renameTab_emptyInputIsNoop() {
        let id = injectTab(title: "Original")
        appState.renameTab(id: id, to: "   ")

        let after = appState.tab(for: id)
        XCTAssertEqual(after?.title, "Original")
        XCTAssertFalse(after?.titleManuallySet ?? true,
                       "Empty rename must not mark the tab as manually set.")
    }

    // MARK: - Auto-title guard

    /// Requirement: once a user renames a tab, Claude's session-title
    /// emissions must not overwrite it.
    func test_applyAutoTitle_skipsAfterManualRename() {
        let id = injectTab(title: "New tab")
        appState.renameTab(id: id, to: "My session")

        appState.applyAutoTitle(tabId: id, rawTitle: "late-arriving-session")
        XCTAssertEqual(appState.tab(for: id)?.title, "My session",
                       "applyAutoTitle must skip tabs the user has renamed.")
    }

    /// Requirement: locking one tab's title must not prevent other tabs
    /// from still receiving auto-titles.
    func test_applyAutoTitle_onOtherTabsIsUnaffectedByRename() {
        let renamedId = injectTab(title: "New tab")
        let otherId = injectTab(title: "New tab", projectPath: "/tmp/rename-other")

        appState.renameTab(id: renamedId, to: "Manual name")
        appState.applyAutoTitle(tabId: otherId, rawTitle: "fix-some-bug")

        XCTAssertEqual(appState.tab(for: renamedId)?.title, "Manual name",
                       "The renamed tab must keep its manual title.")
        XCTAssertEqual(appState.tab(for: otherId)?.title, "Fix some bug",
                       "Other tabs must still receive auto-titles from Claude.")
        XCTAssertTrue(appState.tab(for: otherId)?.titleAutoGenerated ?? false)
        XCTAssertFalse(appState.tab(for: otherId)?.titleManuallySet ?? true)
    }

    func test_applyAutoTitle_stillWorksOnFreshTab() {
        let id = injectTab(title: "New tab")
        appState.applyAutoTitle(tabId: id, rawTitle: "fix-top-bar-height")

        let after = appState.tab(for: id)
        XCTAssertEqual(after?.title, "Fix top bar height")
        XCTAssertTrue(after?.titleAutoGenerated ?? false)
        XCTAssertFalse(after?.titleManuallySet ?? true)
    }

    /// Drives the real OSC entry point (`paneTitleChanged`) the same way
    /// `AppStateStatusDotTests` does, to confirm the guard holds at the
    /// public API and not just at `applyAutoTitle`.
    func test_paneTitleChanged_afterRename_doesNotClobber() {
        let id = injectTab(title: "New tab", withClaudePane: true)
        guard let claudePaneId = appState.tab(for: id)?
            .panes.first(where: { $0.kind == .claude })?.id
        else {
            XCTFail("Injected tab should have a Claude pane")
            return
        }

        appState.renameTab(id: id, to: "Manual name")
        appState.paneTitleChanged(
            tabId: id, paneId: claudePaneId, title: "\u{2800} new-session-name"
        )
        XCTAssertEqual(appState.tab(for: id)?.title, "Manual name",
                       "paneTitleChanged must not clobber a manually renamed tab.")
    }

    // MARK: - Persistence

    /// A manual rename must survive an app relaunch — the user's tab
    /// label is useless if quitting Nice throws it away.
    func test_manualRename_roundTripsThroughPersistedWindow() {
        let id = injectTab(title: "New tab")
        appState.renameTab(id: id, to: "Keep me")

        let snapshot = appState.snapshotPersistedWindow()
        let persistedTab = snapshot.projects
            .flatMap(\.tabs)
            .first(where: { $0.id == id })
        XCTAssertEqual(persistedTab?.title, "Keep me")
        XCTAssertEqual(persistedTab?.titleManuallySet, true,
                       "Manually renamed tabs must persist their titleManuallySet flag so post-relaunch auto-titles still skip them.")
    }

    // MARK: - Helpers

    /// Build a `Tab` directly in `projects` without spawning a pty.
    /// Fast, deterministic ids, and supports creating multiple distinct
    /// tabs in the same test.
    @discardableResult
    private func injectTab(
        title: String,
        projectPath: String = "/tmp/rename-test",
        withClaudePane: Bool = false
    ) -> String {
        let uid = UUID().uuidString
        let tabId = "t-\(uid)"
        let panes: [Pane] = withClaudePane
            ? [Pane(id: "\(tabId)-claude", title: "Claude", kind: .claude)]
            : [Pane(id: "\(tabId)-term", title: "Terminal", kind: .terminal)]
        let tab = Tab(
            id: tabId,
            title: title,
            cwd: projectPath,
            branch: nil,
            panes: panes,
            activePaneId: panes.first?.id
        )
        if let idx = appState.projects.firstIndex(where: { $0.path == projectPath }) {
            appState.projects[idx].tabs.append(tab)
        } else {
            let project = Project(
                id: "p-\(uid)",
                name: (projectPath as NSString).lastPathComponent,
                path: projectPath,
                tabs: [tab]
            )
            appState.projects.append(project)
        }
        return tabId
    }
}
